# Frontend
FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy application code
COPY frontend .

# Build
RUN npm run build

# Serve
EXPOSE 3000

CMD ["npm", "run", "preview"]
